import React from 'react';

function Footer() {
  return (
    <footer>
        <div>
          <p>Fitness+ All Rights Reserved</p>
          <p><a href="http://chiptang.com">chiptang.com</a></p>
          <p><a href="tel:+11234567890">+1 123 456 7890</a></p>
        </div>
        <div>
          <p>Photos Generated by Dall E</p>
          <p><a href="https://github.com/terrenjpeterson/caloriecounter/blob/master/src/data/foods.json">Food Datebase</a></p>
          <p><a href="https://api-ninjas.com/api/caloriesburned">Workout API</a></p>
        </div>
    </footer>
  );
}

export default Footer;
