import React from 'react';

function Footer() {
  return (
    <footer>
        <div>
          <p>Chip Tang ©Chipkin 2024 All rights reserved.</p>
          <p><a href="http://chiptang.com">chiptang.com</a></p>
          <p><a href="tel:+12063212078">+1 206 321 2078</a></p>
        </div>
        <div>
          <p>Photos Generated by Dall E</p>
          <p><a href="https://github.com/terrenjpeterson/caloriecounter/blob/master/src/data/foods.json">Food Datebase</a></p>
          <p><a href="https://api-ninjas.com/api/caloriesburned">Workout API</a></p>
        </div>
    </footer>
  );
}

export default Footer;
